force-app/main/default/objects/Archival_And_Big_Object_Link__c/Archival_And_Big_Object_Link__c.object-meta.xml
<CustomObject>
    <label>Archival And Big Object Link</label>
    <nameField>
        <displayFormat>ABOL-{00000}</displayFormat>
        <label>Link Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Archival And Big Object Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Archival_And_Big_Object_Link__c/fields/Archival_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Archival_Configuration__c</fullName>
    <label>Archival Configuration</label>
    <referenceTo>Archival_Configuration__c</referenceTo>
    <relationshipLabel>Archival And Big Object Links</relationshipLabel>
    <relationshipName>Archival_And_Big_Object_Links1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Archival_And_Big_Object_Link__c/fields/Big_Object_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Big_Object_Configuration__c</fullName>
    <label>Big Object Configuration</label>
    <referenceTo>Big_Object_Configuration__c</referenceTo>
    <relationshipLabel>Archival And Big Object Links</relationshipLabel>
    <relationshipName>Archival_And_Big_Object_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Archival_And_Big_Object_Link__c/fields/Big_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Big_Object_Name__c</fullName>
    <formula>Big_Object_Configuration__r.Big_Object_API_Name__c</formula>
    <label>Big Object Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archival_Configuration__c/Archival_Configuration__c.object-meta.xml
<CustomObject>
    <label>Archival Configuration</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Configuration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Archival Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Archival_Configuration__c/fields/Parent_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object_API_Name__c</fullName>
    <inlineHelpText>Object Name of which archival is related to</inlineHelpText>
    <label>Parent Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archival_Configuration__c/fields/Parent_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object_Name__c</fullName>
    <label>Parent Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archival_Configuration__c/fields/Related_Index_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_Index_Field_API_Name__c</fullName>
    <inlineHelpText>Index field of child object based on which parent record id is used to fetch related records</inlineHelpText>
    <label>Related Index Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archival_Configuration__c/fields/Related_List_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_List_Name__c</fullName>
    <label>Related List Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archival_Configuration__c/fields/Related_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_API_Name__c</fullName>
    <inlineHelpText>Object name of child object that is related to parent object</inlineHelpText>
    <label>Related Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archival_Configuration__c/fields/Related_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Name__c</fullName>
    <label>Related Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Big_Object_Configuration__c/Big_Object_Configuration__c.object-meta.xml
<CustomObject>
    <label>Big Object Configuration</label>
    <nameField>
        <displayFormat>BOC-{00000}</displayFormat>
        <label>Configuration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Big Object Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ConfigurationHomeController.cls
public with sharing class ConfigurationHomeController {

    @AuraEnabled
    public static void deleteArchiveAndBigObjectConfig(string archiveConfigId){
        List<Archival_Configuration__c> archive=[SELECT id,Related_List_Name__c,CreatedDate,Name,Parent_Object_API_Name__c,Parent_Object_Name__c,Related_Index_Field_API_Name__c,Related_Object_API_Name__c,Related_Object_Name__c,(SELECT id,Big_Object_Name__c,Big_Object_Configuration__c FROM Archival_And_Big_Object_Links1__r) FROM Archival_Configuration__c WHERE id=:archiveConfigId];
        String bigObjectConfigId='';
        if(archive.size()>0 && archive.get(0).Archival_And_Big_Object_Links1__r.size()>0){
            bigObjectConfigId=archive.get(0).Archival_And_Big_Object_Links1__r[0].Big_Object_Configuration__c;
        }
        List<Big_Object_Configuration__c> big=[SELECT id FROM Big_Object_Configuration__c WHERE id=:bigObjectConfigId];
        if(big.size()>0) delete big;
        if(archive.size()>0) delete archive;
        
    }

    @AuraEnabled(cacheable=true)
    public static List<Archival_Configuration__c> getAllArchivalConfiguration(){
        return [SELECT id,Related_List_Name__c,CreatedDate,Name,Parent_Object_API_Name__c,Parent_Object_Name__c,Related_Index_Field_API_Name__c,Related_Object_API_Name__c,Related_Object_Name__c,(SELECT id,Big_Object_Name__c,Big_Object_Configuration__c FROM Archival_And_Big_Object_Links1__r) FROM Archival_Configuration__c];
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String,String> getAllObjects(){
        Map<String,String> apiAndNameMap=new Map<String,String>();
        for(DescribeSObjectResult obj:SDescribeUtility.getAllObjects().values()){
            apiAndNameMap.put(obj.getName(),obj.getLabel());
        }
        return apiAndNameMap;
    }

    @AuraEnabled
    public static void createArchiveConfig(String parentObjectApiName,String childObjectApiName,
    String childObjectRelatedFieldName,
    List<String> childObjectFields){
        Set<String> childIndexFields=new Set<String>();
        childIndexFields.add('Id');
        childIndexFields.add(childObjectRelatedFieldName);
        Archival_Configuration__c config=ConfigurationEngine.createArchiveConfiguration(parentObjectApiName,childObjectApiName,childObjectRelatedFieldName);

        Big_Object_Configuration__c bigObject=ConfigurationEngine.createBigObjectConfiguration(childObjectApiName, childObjectFields, childIndexFields);

        Archival_And_Big_Object_Link__c link=new Archival_And_Big_Object_Link__c();
        link.Archival_Configuration__c=config.id;
        link.Big_Object_Configuration__c=bigObject.id;
        insert link;
    }
}