force-app/main/default/objects/Archival_And_Big_Object_Link__c/Archival_And_Big_Object_Link__c.object-meta.xml
<CustomObject>
    <label>Archival And Big Object Link</label>
    <nameField>
        <displayFormat>ABOL-{00000}</displayFormat>
        <label>Link Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Archival And Big Object Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Archival_And_Big_Object_Link__c/fields/Archival_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Archival_Configuration__c</fullName>
    <label>Archival Configuration</label>
    <referenceTo>Archival_Configuration__c</referenceTo>
    <relationshipLabel>Archival And Big Object Links</relationshipLabel>
    <relationshipName>Archival_And_Big_Object_Links1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Archival_And_Big_Object_Link__c/fields/Big_Object_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Big_Object_Configuration__c</fullName>
    <label>Big Object Configuration</label>
    <referenceTo>Big_Object_Configuration__c</referenceTo>
    <relationshipLabel>Archival And Big Object Links</relationshipLabel>
    <relationshipName>Archival_And_Big_Object_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Archival_Configuration__c/Archival_Configuration__c.object-meta.xml
<CustomObject>
    <label>Archival Configuration</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Configuration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Archival Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Archival_Configuration__c/fields/Related_Index_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_Index_Field_API_Name__c</fullName>
    <inlineHelpText>Index field of child object based on which parent record id is used to fetch related records</inlineHelpText>
    <label>Related Index Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Big_Object_Configuration__c/Big_Object_Configuration__c.object-meta.xml
<CustomObject>
    <label>Big Object Configuration</label>
    <nameField>
        <displayFormat>BOC-{00000}</displayFormat>
        <label>Configuration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Big Object Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Big_Object_Configuration__c/fields/Big_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Big_Object_API_Name__c</fullName>
    <label>Big Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Big_Object_Field_Configuration__c/Big_Object_Field_Configuration__c.object-meta.xml
<CustomObject>
    <label>Big Object Field Configuration</label>
    <nameField>
        <displayFormat>BOFC-{00000}</displayFormat>
        <label>Configuration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Big Object Field Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Big_Object_Field_Configuration__c/fields/Big_Object_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Big_Object_Configuration__c</fullName>
    <label>Big Object Configuration</label>
    <referenceTo>Big_Object_Configuration__c</referenceTo>
    <relationshipLabel>Big Object Field Configurations</relationshipLabel>
    <relationshipName>Big_Object_Field_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Big_Object_Field_Configuration__c/fields/Big_Object_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Big_Object_Field_API_Name__c</fullName>
    <label>Big Object Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Big_Object_Field_Configuration__c/fields/Related_List_View__c.field-meta.xml
<CustomField>
    <fullName>Related_List_View__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enable to show this field and its value on related list</inlineHelpText>
    <label>Related List View</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Big_Object_Field_Configuration__c/fields/Source_Object_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Object_Field_API_Name__c</fullName>
    <inlineHelpText>API Name of field to be created</inlineHelpText>
    <label>Source Object Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QueryEngine.cls
public with sharing class QueryEngine {


    public static void  generateRelatedListQuery(String archivalConfigId){
        Archival_And_Big_Object_Link__c link=[SELECT id,Archival_Configuration__r.Related_List_Query__c,Archival_Configuration__r.Related_Index_Field_API_Name__c,Archival_Configuration__c,Big_Object_Configuration__c 
        FROM Archival_And_Big_Object_Link__c WHERE Archival_Configuration__c=:archivalConfigId];
        System.debug('link '+link);
        Big_Object_Configuration__c bigObject=[SELECT id,Big_Object_API_Name__c,
        (SELECT id,Big_Object_Field_API_Name__c,Source_Object_Field_API_Name__c 
        FROM Big_Object_Field_Configurations__r WHERE Related_List_View__c=true OR Source_Object_Field_API_Name__c=:link.Archival_Configuration__r.Related_Index_Field_API_Name__c) 
        FROM Big_Object_Configuration__c WHERE id=:link.Big_Object_Configuration__c];

        System.debug('bigObject '+bigObject);
        String query='SELECT ';
        String whereCondition=' FROM '+bigObject.Big_Object_API_Name__c+' WHERE ';
        for(Big_Object_Field_Configuration__c field:bigObject.Big_Object_Field_Configurations__r){
            if(field.Source_Object_Field_API_Name__c==link.Archival_Configuration__r.Related_Index_Field_API_Name__c){
                whereCondition+=field.Big_Object_Field_API_Name__c+'=:RELATED_INDEX_ID ';
            }
            else{
                query+=field.Big_Object_Field_API_Name__c+',';
            }
            
        }
        query.removeEnd(',');
        Archival_Configuration__c config=new Archival_Configuration__c();
        config.id=archivalConfigId;

        config.Related_List_Query__c=query+whereCondition;

        update config;



    }

}